global_costmap:
   global_frame: map
   robot_base_frame: body
   update_frequency: 1.0
   publish_frequency: 0.5
   transform_tolerance: 0.5
   map_topic: /rtabmap/grid_map
   plugins:
     - {name: static_layer,       type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,     type: "costmap_2d::ObstacleLayer"}
     - {name: inflation_layer,    type: "costmap_2d::InflationLayer"}
